Support timezone in slack and ms teams notifications
Graylog2/graylog-plugin-integrations pull request #1320
Opened 2023-02-27 16:45 UTC by kingzacko1

- Support timezones for Slack and Teams notifications
- Convert existing JSX files to TSX files - does not include a conversion to functional components.

Closes #1318
## Notes for Reviewers

- [ ] The commit history must be preserved - please use the rebase-merge or standard merge option instead of squash-merge
- [ ] Sync up with the author before merging

2023-03-06 17:59 UTC, ryan-carroll-graylog commented on src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfig.java
> +    public abstract DateTimeZone timeZone();
@kingzacko1 I'm getting an error if I remove the time zone from the config and then execute a test notification (slack and teams). 

I'm also noticing that if I select `GMT-12` in the config I get `-12` in the resulting notification (and vice versa). Not sure if this is just me misunderstanding how that's supposed to work and you didn't touch any of that conversion code here.

```suggestion
    @Nullable
    public abstract DateTimeZone timeZone();
```
![image](https://user-images.githubusercontent.com/103449971/223192121-cf7d9c7e-ecf2-4d34-b647-beb59a4e61fa.png)

2023-03-06 18:01 UTC, ryan-carroll-graylog requested changes
Other than the time zone comments this looks solid and tests successfully! Old notifications work fine and I really like the other improvements!

2023-03-06 19:23 UTC, kingzacko1 commented on src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfig.java
> +    public abstract DateTimeZone timeZone();
The idea was to require a time zone, but just default to UTC (as it has always been) if the field is never set. Let me remove the ability to clear the time zone. 

The `GMT-12` one may be a different issue, but I will check it out.

2023-03-06 19:26 UTC, ryan-carroll-graylog commented on src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfig.java
> +    public abstract DateTimeZone timeZone();
Ok makes sense to me. Just a heads up in case you're not already tracking, the UI says `(optional)` for that field so that should probably go too.

2023-03-06 20:07 UTC, kingzacko1 commented on src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfig.java
> +    public abstract DateTimeZone timeZone();
@ryan-carroll-graylog and I don't understand it either... but look at [this list](https://www.ibm.com/docs/en/cloudpakw3700/2.3.0.0?topic=SS6PD2_2.3.0/doc/psapsys_restapi/time_zone_list.htm) of time zones and see that `Etc/GMT-12` is GMT+12 and `Etc/GMT+12` is GMT-12.... ¯\\\_(ツ)_/¯

2023-03-06 20:14 UTC, ryan-carroll-graylog commented on src/main/java/org/graylog/integrations/notifications/types/SlackEventNotificationConfig.java
> +    public abstract DateTimeZone timeZone();
Ah well there ya go. Figured it was something like that, with the alternative being that it been broken everywhere else we're doing similar and nobody noticed.

2023-03-06 20:39 UTC, ryan-carroll-graylog approved these changes
LGTM with the latest!

2023-03-14 17:49 UTC, zeeklop approved these changes
LGTM

2023-03-22 21:15 UTC, merged